const c=navigator.userAgent;var d=navigator.appName,e=`${parseFloat(navigator.appVersion)}`;let k=parseInt(navigator.appVersion,10),m,n,q;
-1!=(n=c.indexOf("Opera"))?(d="Opera",e=c.substring(n+6),-1!=(n=c.indexOf("Version"))&&(e=c.substring(n+8))):-1!=(n=c.indexOf("MSIE"))?(d="Microsoft Internet Explorer",e=c.substring(n+5)):-1!=(n=c.indexOf("Chrome"))?(d="Chrome",e=c.substring(n+7)):-1!=(n=c.indexOf("Safari"))?(d="Safari",e=c.substring(n+7),-1!=(n=c.indexOf("Version"))&&(e=c.substring(n+8))):-1!=(n=c.indexOf("Firefox"))?(d="Firefox",e=c.substring(n+8)):-1!=c.indexOf("Trident/")?(d="Microsoft Internet Explorer",e=c.substring(c.indexOf("rv:")+
3)):(m=c.lastIndexOf(" ")+1)<(n=c.lastIndexOf("/"))&&(d=c.substring(m,n),e=c.substring(n+1),d.toLowerCase()==d.toUpperCase()&&(d=navigator.appName));-1!=(q=e.indexOf(";"))&&(e=e.substring(0,q));-1!=(q=e.indexOf(" "))&&(e=e.substring(0,q));-1!=(q=e.indexOf(")"))&&(e=e.substring(0,q));k=parseInt(`${e}`,10);isNaN(k)&&(e=`${parseFloat(navigator.appVersion)}`,k=parseInt(navigator.appVersion,10));var r=!!navigator.cookieEnabled;
"undefined"!==typeof navigator.cookieEnabled||r||(document.cookie="testcookie",r=-1!=document.cookie.indexOf("testcookie"));var t="-";
const u=[{g:"Windows 10",r:/(Windows 10.0|Windows NT 10.0)/},{g:"Windows 8.1",r:/(Windows 8.1|Windows NT 6.3)/},{g:"Windows 8",r:/(Windows 8|Windows NT 6.2)/},{g:"Windows 7",r:/(Windows 7|Windows NT 6.1)/},{g:"Windows Vista",r:/Windows NT 6.0/},{g:"Windows Server 2003",r:/Windows NT 5.2/},{g:"Windows XP",r:/(Windows NT 5.1|Windows XP)/},{g:"Windows 2000",r:/(Windows NT 5.0|Windows 2000)/},{g:"Windows ME",r:/(Win 9x 4.90|Windows ME)/},{g:"Windows 98",r:/(Windows 98|Win98)/},{g:"Windows 95",r:/(Windows 95|Win95|Windows_95)/},
{g:"Windows NT 4.0",r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{g:"Windows CE",r:/Windows CE/},{g:"Windows 3.11",r:/Win16/},{g:"Android",r:/Android/},{g:"Open BSD",r:/OpenBSD/},{g:"Sun OS",r:/SunOS/},{g:"Linux",r:/(Linux|X11)/},{g:"iOS",r:/(iPhone|iPad|iPod)/},{g:"Mac OS X",r:/Mac OS X/},{g:"Mac OS",r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{g:"QNX",r:/QNX/},{g:"UNIX",r:/UNIX/},{g:"BeOS",r:/BeOS/},{g:"OS/2",r:/OS\/2/},{g:"Search Bot",r:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}];
for(const f in u){const a=parseInt(u[f]);if(a.r.test(c)){t=a.g;break}}/Windows/.test(t)&&(t="Windows");let v;
if("undefined"!==typeof navigator.plugins&&"object"===typeof navigator.plugins["Shockwave Flash"])v=navigator.plugins["Shockwave Flash"].description,!v||"undefined"!==typeof navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&!navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(v=v.replace(/^.*\s+(\S+\s+\S+$)/,"$1"));else if("undefined"!==typeof this.ActiveXObject)try{(v=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))&&(v=v.split(" ")[1].split(","))}catch(f){}
(async function(){w();console.log("newData",{width:window.innerWidth,height:window.innerHeight,j:screen.height,l:screen.width,C:screen.availWidth,colorDepth:screen.colorDepth,pixelDepth:screen.pixelDepth,href:window.location.href,hostname:window.location.hostname,pathname:window.location.pathname,protocol:window.location.protocol,language:navigator.language,onLine:navigator.onLine,appName:navigator.appName,appCodeName:navigator.appCodeName,product:navigator.product});var f=await x();console.log("curruntIp",
f);f=await y(f);console.log("constIp",f)})();
async function w(){var f=(void 0).i,a=navigator.userAgent;let h=navigator.appName,g=`${parseFloat(navigator.appVersion)}`;var l,b;let p;-1!=(b=a.indexOf("Opera"))?(h="Opera",g=a.substring(b+6),-1!=(b=a.indexOf("Version"))&&(g=a.substring(b+8))):-1!=(b=a.indexOf("MSIE"))?(h="Microsoft Internet Explorer",g=a.substring(b+5)):-1!=(b=a.indexOf("Chrome"))?(h="Chrome",g=a.substring(b+7)):-1!=(b=a.indexOf("Safari"))?(h="Safari",g=a.substring(b+7),-1!=(b=a.indexOf("Version"))&&(g=a.substring(b+8))):-1!=(b=
a.indexOf("Firefox"))?(h="Firefox",g=a.substring(b+8)):(l=a.lastIndexOf(" ")+1)<(b=a.lastIndexOf("/"))&&(h=a.substring(l,b),g=a.substring(b+1),h.toLowerCase()==h.toUpperCase()&&(h=navigator.appName));-1!=(p=g.indexOf(";"))&&(g=g.substring(0,p));-1!=(p=g.indexOf(" "))&&(g=g.substring(0,p));a=parseInt(`${g}`,10);isNaN(a)&&(g=`${parseFloat(navigator.appVersion)}`,a=parseInt(navigator.appVersion,10));l="Unknown OS";-1!=navigator.appVersion.indexOf("Win")&&(l="Windows");-1!=navigator.appVersion.indexOf("Mac")&&
(l="MacOS");-1!=navigator.appVersion.indexOf("X11")&&(l="UNIX");-1!=navigator.appVersion.indexOf("Linux")&&(l="Linux");b=window.location;f={u:window.matchMedia("(pointer:coarse)").matches,o:h,version:g,v:a,m:navigator.appName,N:navigator.userAgent,A:l,D:b.hash,F:b.host,G:b.hostname,H:b.href,I:b.origin,J:b.pathname,K:b.port,L:b.protocol,M:b.search,i:f,h:null,B:window.devicePixelRatio,colorDepth:screen.colorDepth,l:screen.width,j:screen.height,language:navigator.language,product:navigator.product};
console.log("userAgentInfo",f)}function x(){return new Promise(f=>{fetch("https://api.ipify.org?format=json").then(a=>a.json()).then(a=>{f(a.h);document.getElementById("ip-address").textContent=a.h}).catch(a=>{console.error("Error fetching IP address:",a);f(null)})})}
function y(f){return new Promise(a=>{fetch(`http://localhost:3000/api/get-ip-info?ip=${f}`,{method:"POST",body:JSON.stringify({s:f})}).then(h=>h.json()).then(h=>{a(h)}).catch(h=>{console.error("Error fetching IP address:",h);a(null)})})};
